moto_gpt_config_path: "/group/40101/milkcychen/Moto/moto_gpt/configs/models/actPredTrue_motionPredTrue_visionMaeLarge_seq2_chunk5_maskProb0.5.yaml"
latent_motion_tokenizer_path: "/group/40101/milkcychen/Moto/latent_motion_tokenizer/checkpoints/latent_motion_tokenizer_trained_on_calvin"
dataset_config_path: "/group/40101/milkcychen/Moto/moto_gpt/configs/data/calvin.yaml"
dataloader_config:
  bs_per_gpu: 16
  workers_per_gpu: 7
  prefetch_factor: 2
rgb_preprocessor_config: 
  model_vision_type: "mae"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true
training_config:
  num_epochs: 20
  num_warmup_epochs: 1
  print_steps: 200
  lr_max: 0.0002
  weight_decay: 0.0001
  gradient_accumulation_steps: 8
  save_epochs: 1
  save_steps: 10000
  save_path: "/group/40101/milkcychen/Moto/moto_gpt/outputs/moto_gpt_finetuned_on_calvin/data_calvin-model_actPredTrue_motionPredTrue_visionMaeLarge_seq2_chunk5_maskProb0.5-train_lr0.0002_bs512-aug_shiftTrue_resizedCropFalse-resume_from_predLatentOnly_calvin_Epoch10"
  resume_ckpt_path: "/group/40101/milkcychen/Moto/moto_gpt/checkpoints/moto_gpt_pretrained_on_calvin/"
  max_epoch: 20
  pred_binary_gripper_action: true