latent_motion_tokenizer_config_path: "/home/v-wenhuitan/wenke_workspace/wenke_data/workspace/action_token_for_offline_rl/latent_motion_tokenizer/configs/models/conv_decoder_base.yaml"
dataset_config_path: "/home/v-wenhuitan/wenke_workspace/wenke_data/workspace/action_token_for_offline_rl/latent_motion_tokenizer/configs/data/pizza.yaml"
dataloader_config:
  bs_per_gpu: 1
  workers_per_gpu: 8
  prefetch_factor: 2
rgb_preprocessor_config: 
  model_vision_type: "dinov2"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true
training_config:
  num_epochs: 20
  num_warmup_epochs: 1
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 2
  save_epochs: 1
  save_steps: 1000
  save_path: "/home/v-wenhuitan/wenke_workspace/wenke_data/workspace/action_token_for_offline_rl/results"
  resume_ckpt_path: null