latent_motion_tokenizer_config_path: "configs/models/base.yaml"
dataset_config_path: "configs/data/bridge_submit.yaml"
dataloader_config:
  bs_per_gpu: 8
  workers_per_gpu: 4
  prefetch_factor: 2
rgb_preprocessor_config: 
  model_vision_type: "mae"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true
training_config:
  num_epochs: 20
  num_warmup_epochs: 1
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 2
  save_epochs: 1
  save_steps: 1000
  save_path: "../moto_results"
  resume_ckpt_path: null